### ISSUE TITLE
fix or drop php 7.4 support

### ISSUE THREAD

**Issue by pradtke** [cirrusidentity/simplesamlphp-module-msverifiedid#2]
```
Problem 1
    - ramsey/uuid[4.6.0, ..., 4.7.3] require php ^8.0 -> your php version (7.4.33) does not satisfy that requirement
 ```

as is, I can't install into php 7.4.
I suppose we could just drop php 7.4 support and only do 8.
or if @windhamg  think that's the only php 8 dependency then we can accept an earlier version (4.2)

**Comment by windhamg** [comment]
Changed ramsey/uuid version dependency to ~4.2.3
